config/routes.rb
Rails.application.routes.draw do

resources :cocktails, only: [:index, :new, :create, :show] do
  resources :doses, only: [:new, :create]
  end
resources :doses, only: [:show, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  accepts_nested_attributes_for :ingredients, allow_destroy: false
  accepts_nested_attributes_for :doses, allow_destroy: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id, message: "Comination should be unique" }

  belongs_to :ingredient
  belongs_to :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new # needed to instantiate the form_for
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    # Will raise ActiveModel::ForbiddenAttributesError
    # need strong params

    # no need for app/views/restaurants/create.html.erb
    redirect_to cocktail_path(@cocktail)
  end


  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
    # also need permit dose & INGREDIENTs, how to write it though ?
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
     # needed to instantiate the form_for
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    @dose.save

    redirect_to cocktail_path(@cocktail)
  end

  def show
    @dose = Dose.find(params[:id])
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
    # also nee
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>See all the Cocktails</h1>
<ul>
  <% @cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail %></li>
  <% end %>
</ul>

<%= link_to "Add a new Cocktail", new_cocktail_path %>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h1>Add a Cocktail</h1>
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
       <!--  <%= f.input :doses %>
        <%= f.input :ingredients %> -->
        <%= f.submit "Add a cocktail", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<h2>Recipe</h2>

<ul>
    <% @cocktail.doses.each do |dose| %>
         <li> <%= dose.description %>
        <%= dose.ingredient.name %> </li>
        <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
      <% end %>
</ul>



<%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), class: 'btn btn-secondary' %>

<%= link_to "See all the cocktails", cocktails_path, class: 'btn btn-secondary' %>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h1>Add a Dose</h1>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <%= f.submit "Done", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/doses/show.html.erb
<h1><%= @dose.description %></h1>


<%= link_to 'Destroy', cocktails_path, method: :delete %>


<%= link_to "See all the cocktails", cocktails_path, class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>